FROM image_test
RUN dotnet publish -r --self-contained win-x64 "./ToDoListAPI.sln" -c Release -o /app/publish/win-x64
RUN dotnet publish -r --self-contained linux-x64 "./ToDoListAPI.sln" -c Release -o /app/publish/linux-x64
RUN dotnet publish -r --self-contained osx-x64 "./ToDoListAPI.sln" -c Release -o /app/publish/osx-x64